import type { FirmSettings, Project, QuoteItem, RateCardItem } from './types';
const id = () => crypto.randomUUID();
const item = (
  name: string,
  description: string,
  unit: QuoteItem['measurementType'],
  rates: [number, number, number],
  length: number,
  width: number,
): QuoteItem => ({
  id: id(),
  name,
  description,
  enabled: true,
  measurementType: unit,
  quantity: 1,
  length,
  width,
  height: 0,
  rates: { standard: rates[0], premium: rates[1], luxury: rates[2] },
  discount: 0,
  notes: '',
  subUnits: [],
});
export const rateCard: RateCardItem[] = [
  [
    'Wardrobe',
    'Modular wardrobe with internal fittings',
    'sqft',
    [1450, 1850, 2400],
  ],
  ['TV Unit', 'Storage-led media console', 'sqft', [1200, 1500, 2000]],
  ['False Ceiling', 'Gypsum ceiling with channels', 'sqft', [140, 180, 240]],
  ['Base Cabinets', 'Modular kitchen base units', 'rft', [9000, 11500, 14500]],
  ['Wall Cabinets', 'Modular kitchen wall units', 'rft', [7500, 9200, 12000]],
  ['Bed Back Panel', 'Upholstered feature panel', 'sqft', [850, 1100, 1550]],
].map(([name, description, unit, rates]) => ({
  id: id(),
  name: name as string,
  description: description as string,
  unit: unit as QuoteItem['measurementType'],
  rates: {
    standard: (rates as number[])[0],
    premium: (rates as number[])[1],
    luxury: (rates as number[])[2],
  },
  subUnits: [],
}));
export const firmSettings: FirmSettings = {
  firmName: 'INTERIX',
  letterheadName: 'Interix Design Studio',
  tagline: 'Interior architecture · thoughtfully estimated',
  gstNumber: '29ABCDE1234F1Z5',
  address: 'Indiranagar, Bengaluru, Karnataka 560038',
  phone: '+91 98765 43210',
  email: 'studio@interix.in',
  quotationNotes: 'Rates are valid for 30 days from the quotation date.',
  terms:
    '50% advance on confirmation. Taxes and statutory charges are additional where applicable. Final measurements will be verified on site.',
  thankYou: 'Thank you for trusting Interix with your home.',
  enabledTiers: ['standard', 'premium', 'luxury'],
};
export const sampleProject: Project = {
  id: id(),
  clientName: 'Arjun Sharma',
  propertyName: 'Sharma Residence',
  layout: '4 BHK',
  carpetArea: 2400,
  defaultTier: 'premium',
  status: 'active',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  projectDiscount: 50000,
  showRates: true,
  rooms: [
    {
      id: id(),
      name: 'Living Room',
      items: [
        item(
          'False Ceiling',
          'Gypsum ceiling with cove lighting',
          'sqft',
          [140, 180, 240],
          18,
          14,
        ),
        item(
          'TV Unit',
          'Full-height veneer media wall',
          'sqft',
          [1200, 1500, 2000],
          10,
          7,
        ),
        item(
          'Mandir',
          'Custom fluted prayer unit',
          'flat',
          [65000, 92000, 140000],
          1,
          1,
        ),
      ],
    },
    {
      id: id(),
      name: 'Kitchen',
      items: [
        item(
          'Base Cabinets',
          'Premium modular base cabinets',
          'rft',
          [9000, 11500, 14500],
          18,
          0,
        ),
        item(
          'Wall Cabinets',
          'Overhead cabinets with soft-close',
          'rft',
          [7500, 9200, 12000],
          14,
          0,
        ),
        item(
          'Tall Unit',
          'Appliance and pantry tower',
          'flat',
          [70000, 95000, 135000],
          1,
          1,
        ),
      ],
    },
    {
      id: id(),
      name: 'Master Bedroom',
      items: [
        item(
          'Wardrobe',
          'Floor-to-ceiling hinged wardrobe',
          'sqft',
          [1450, 1850, 2400],
          12,
          8,
        ),
        item(
          'Bed Back Panel',
          'Upholstered feature wall',
          'sqft',
          [850, 1100, 1550],
          12,
          7,
        ),
      ],
    },
    {
      id: id(),
      name: 'Kids Bedroom',
      items: [
        item(
          'Wardrobe',
          'Wardrobe with study-side storage',
          'sqft',
          [1450, 1850, 2400],
          9,
          8,
        ),
        item(
          'Study Unit',
          'Desk, drawers and overheads',
          'rft',
          [6500, 8200, 10500],
          7,
          0,
        ),
      ],
    },
    {
      id: id(),
      name: 'Guest Bedroom',
      items: [
        item(
          'Wardrobe',
          'Compact guest wardrobe',
          'sqft',
          [1450, 1850, 2400],
          7,
          8,
        ),
        item(
          'TV Unit',
          'Wall-mounted media ledge',
          'rft',
          [5500, 7200, 9500],
          6,
          0,
        ),
      ],
    },
  ],
  fees: [
    {
      id: id(),
      name: 'Design Fee',
      method: 'sqft',
      value: 50,
      discount: 0,
      enabled: true,
    },
    {
      id: id(),
      name: '3D / Drawing',
      method: 'flat',
      value: 35000,
      discount: 0,
      enabled: true,
    },
    {
      id: id(),
      name: 'Site Supervision',
      method: 'flat',
      value: 45000,
      discount: 0,
      enabled: true,
    },
  ],
};
